site_name: HR analytics
site_description: HR analytics
site_url: https://zuydstats.github.io/HRa/

repo_name: ZuydStats/HRa
repo_url: https://github.com/ZuydStats/HRa

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Important information:
    - About the Course FAQ: important-information/faq.md
    - Test yourself exam: important-information/test-your-self-exam.md
  - Week 1:
    - HRa1 - Welcome to HR analytics: week-01/hra1.md
    - HRa2 - Research questions and hypotheses: week-01/hra2.md
  - Week 2:
    - HRa1 - Quantitative analyses and Type I & II errors: week-02/hra1.md
    - HRa2 -  Reliability, Validity and Sampling: week-02/hra2.md
    - HRa3 - Workshop - Introduction to JAMOVI and the Myriad hotel case: week-02/workshop.md
    - Answer keys: week-02/answer-keys.md
  - Week 3:
    - HRa1 - Descriptives & graphs: week-03/hra1.md
    - HRa2 - Estimation and Hypothesis testing: week-03/hra2.md
    - HRa3 - Workshop - OCAI: week-03/workshop.md
  - Week 4:
    - HRa1 - Test Yourself what graph to use: week-04/hra1.md
    - HRa2 - Crosstabs and the chi-square test: week-04/hra2.md
    - HRa3 - Workshop - People Power Planning: week-04/workshop.md
  - Week 5:
    - HRa1 - Correlation: week-05/hra1.md
    - HRa2 - Ttest: week-05/hra2.md
    - HRa3 - Workshop - Satisfaction: week-05/workshop.md
  - Week 6:
    - HRa1 - ANOVA : week-06/hra1.md
    - HRa2 - Test overview & Exam prep: week-06/hra2.md
    - Hra3 - Workshop - Performance Appraisal: week-06/workshop.md
  - Week 7:
    - HRa1 - Turnover: week-07/hra1.md
  - Week 8:
    - HRa1 - Myriad: week-08/hra1.md
    - HRa2 - Q/A: week-08/hra2.md
  - Additional materials: additional-materials/additional.md


